### ISSUE TITLE
Deploying error with empty file

### ISSUE THREAD

**Issue by QuentinLemCode** [1MB/1mb-cli#6]
I have tried to deploy a simple site with 3 files :

- index.html (very basic with a link to a style.css and a script.js)
- style.css
- script.js

style.css and script.js are empty

Deploying with 1mb-cli deploy give this : 
````
D:\Develop\zbeul-site>1mb-cli deploy
(node:155836) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(data)

    at AsyncFunction.module.exports [as js] (d:\Profiles\qlemeasle\AppData\Roaming\npm\node_modules\1mb-cli\node_modules\minify\lib\js.js:12:5)
    at onDataRead (d:\Profiles\qlemeasle\AppData\Roaming\npm\node_modules\1mb-cli\node_modules\minify\lib\minify.js:74:44)
    at optimize (d:\Profiles\qlemeasle\AppData\Roaming\npm\node_modules\1mb-cli\node_modules\minify\lib\minify.js:62:12)
(node:155836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:155836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:155836) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(data)

    at AsyncFunction.module.exports [as css] (d:\Profiles\qlemeasle\AppData\Roaming\npm\node_modules\1mb-cli\node_modules\minify\lib\css.js:14:5)
    at onDataRead (d:\Profiles\qlemeasle\AppData\Roaming\npm\node_modules\1mb-cli\node_modules\minify\lib\minify.js:74:44)
    at optimize (d:\Profiles\qlemeasle\AppData\Roaming\npm\node_modules\1mb-cli\node_modules\minify\lib\minify.js:62:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:155836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
Deploying...... !
(node:155836) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  assert(data)
    at AsyncFunction.module.exports [as css] (d:/Profiles/qlemeasle/AppData/Roaming/npm/node_modules/1mb-cli/node_modules/minify/lib/css.js:14:5)
    at onDataRead (d:/Profiles/qlemeasle/AppData/Roaming/npm/node_modules/1mb-cli/node_modules/minify/lib/minify.js:74:44)
    at optimize (d:/Profiles/qlemeasle/AppData/Roaming/npm/node_modules/1mb-cli/node_modules/minify/lib/minify.js:62:12)

````

Using Windows 10 Enterprise x64  with cmd 
node 10.15.0
npm 6.4.1

**Comment by 0x15f** [comment]
Fixed in latest release.
